### ISSUE TITLE
Evento VipUtils.js - remover vip

### ISSUE THREAD

**Issue by gelones** [zSpl1nterUS/Bot-Tutorial#3]
Assisti a vídeo aula 50, onde você ensinou a criar um sistema para remover o vip (obrigado).
Vou fazendo junto com o vídeo, mas tive uma dificuldade porque o metodo dos meus eventos são diferentes do seu.

os seus eventos começam com 

```javascript



module.exports = class {
  constructor(client) {
    this.client = client;
  }

  async run() {
    this.client.on("ready", async () => {
      await this.VipFilter();
    });
  }

````

Assim não funcionando no meu bot, quando eu coloco até um console.log('Teste') ele não envia no console porque não ligou o evento, assim não removendo o vip.

Já o codigo do meu evento é este abaixo a maneira em que ele começa, e meio que eu não consegui adaptar o sistema dentro do meu codigo dava tudo errado e ficava com muitos erros.

Você pode da uma ajuda?

```javascript

client.on("ready", () => { //  Meus eventos começam assim
// codigo
});

```

ou assim

```javascript

client.on('guildMemberAdd', async member => {
// codigo
})

```

**Comment by ShadowGameszz** [comment]
Você pode usar seu codigo assim:

````js
const VipFilter = require('local do arquivo.')
client.on('ready', async () => {
    await VipFilter();
}

**Comment by gelones** [comment]
> Você pode usar seu codigo assim:
> 
> ```js
> const VipFilter = require('local do arquivo.')
> client.on('ready', async () => {
>     await VipFilter();
> }
> ```

oque eu estou dizendo é colocar todo o codigo do VipUtils.js 

Dentro disso

```javascript
client.on('ready', async () => {
  
}
```

exemplo

```javascript

client.on("ready", async () => {
      await this.VipFilter();
    });
  }
  async VipFilter() {
    setInterval(async () => {
      const list_vips = await require("mongoose")
        .connection.collection("users")
        .find({ "vip.date": { $gt: 1 } })
        .toArray();

      const filter_members = Object.entries(list_vips).filter(
        ([, x]) => x.vip.date <= Date.now()
      );

      const VIPS = filter_members.map(([, x]) => x.idU);

      await this.VipRemove(VIPS);
    }, 60000);
  }

  async VipRemove(VIPS) {
    let totalPessoas = VIPS.length;
    let size = 0;

    const interval = setInterval(async () => {
      if (totalPessoas <= 0) clearInterval(interval);
      else {
        let members = VIPS[size++];

        const user = await this.client.users.fetch(members);

        //const doc = await this.client.database.users.findOne({id: user.id})

        await this.client.database.users.findOneAndUpdate(
          { idU: user.id },
          { $set: { "vip.date": 0, "vip.hasVip": false } }
        );
      }

      totalPessoas--;
    }, 5000);
  }

```

assim funcionaria mas ta dando muito erro

**Comment by ShadowGameszz** [comment]
```js
client.on("ready", async () => {
      await VipFilter();
    });
  }
  async VipFilter() {
    setInterval(async () => {
      const list_vips = await require("mongoose")
        .connection.collection("users")
        .find({ "vip.date": { $gt: 1 } })
        .toArray();

      const filter_members = Object.entries(list_vips).filter(
        ([, x]) => x.vip.date <= Date.now()
      );

      const VIPS = filter_members.map(([, x]) => x.idU);

      await VipRemove(VIPS);
    }, 60000);
  }

  async VipRemove(VIPS) {
    let totalPessoas = VIPS.length;
    let size = 0;

    const interval = setInterval(async () => {
      if (totalPessoas <= 0) clearInterval(interval);
      else {
        let members = VIPS[size++];

        const user = await client.users.fetch(members);

        //const doc = await client.database.users.findOne({id: user.id})

        await client.database.users.findOneAndUpdate(
          { idU: user.id },
          { $set: { "vip.date": 0, "vip.hasVip": false } }
        );
      }

      totalPessoas--;
    }, 5000);
  }

**Comment by gelones** [comment]
> ```js
> client.on("ready", async () => {
>       await VipFilter();
>     });
>   }
>   async VipFilter() {
>     setInterval(async () => {
>       const list_vips = await require("mongoose")
>         .connection.collection("users")
>         .find({ "vip.date": { $gt: 1 } })
>         .toArray();
> 
>       const filter_members = Object.entries(list_vips).filter(
>         ([, x]) => x.vip.date <= Date.now()
>       );
> 
>       const VIPS = filter_members.map(([, x]) => x.idU);
> 
>       await VipRemove(VIPS);
>     }, 60000);
>   }
> 
>   async VipRemove(VIPS) {
>     let totalPessoas = VIPS.length;
>     let size = 0;
> 
>     const interval = setInterval(async () => {
>       if (totalPessoas <= 0) clearInterval(interval);
>       else {
>         let members = VIPS[size++];
> 
>         const user = await client.users.fetch(members);
> 
>         //const doc = await client.database.users.findOne({id: user.id})
> 
>         await client.database.users.findOneAndUpdate(
>           { idU: user.id },
>           { $set: { "vip.date": 0, "vip.hasVip": false } }
>         );
>       }
> 
>       totalPessoas--;
>     }, 5000);
>   }
> ```

[Erro print](https://i.imgur.com/DAxaBwe.png)
@ShadowGameszz @zSpl1nterUS

**Comment by ShadowGameszz** [comment]
> > ```js
> > client.on("ready", async () => {
> >       await VipFilter();
> >     });
> >   }
> >   async VipFilter() {
> >     setInterval(async () => {
> >       const list_vips = await require("mongoose")
> >         .connection.collection("users")
> >         .find({ "vip.date": { $gt: 1 } })
> >         .toArray();
> > 
> >       const filter_members = Object.entries(list_vips).filter(
> >         ([, x]) => x.vip.date <= Date.now()
> >       );
> > 
> >       const VIPS = filter_members.map(([, x]) => x.idU);
> > 
> >       await VipRemove(VIPS);
> >     }, 60000);
> >   }
> > 
> >   async VipRemove(VIPS) {
> >     let totalPessoas = VIPS.length;
> >     let size = 0;
> > 
> >     const interval = setInterval(async () => {
> >       if (totalPessoas <= 0) clearInterval(interval);
> >       else {
> >         let members = VIPS[size++];
> > 
> >         const user = await client.users.fetch(members);
> > 
> >         //const doc = await client.database.users.findOne({id: user.id})
> > 
> >         await client.database.users.findOneAndUpdate(
> >           { idU: user.id },
> >           { $set: { "vip.date": 0, "vip.hasVip": false } }
> >         );
> >       }
> > 
> >       totalPessoas--;
> >     }, 5000);
> >   }
> > ```
> 
> [Erro print](https://i.imgur.com/DAxaBwe.png)
> @ShadowGameszz @zSpl1nterUS
```client.on("ready", async () => {
      await VipFilter();
    });
  },
  async VipFilter() {
    setInterval(async () => {
      const list_vips = await require("mongoose")
        .connection.collection("users")
        .find({ "vip.date": { $gt: 1 } })
        .toArray();

      const filter_members = Object.entries(list_vips).filter(
        ([, x]) => x.vip.date <= Date.now()
      );

      const VIPS = filter_members.map(([, x]) => x.idU);

      await VipRemove(VIPS);
    }, 60000);
  },

  async VipRemove(VIPS) {
    let totalPessoas = VIPS.length;
    let size = 0;

    const interval = setInterval(async () => {
      if (totalPessoas <= 0) clearInterval(interval);
      else {
        let members = VIPS[size++];

        const user = await client.users.fetch(members);

        //const doc = await client.database.users.findOne({id: user.id})

        await client.database.users.findOneAndUpdate(
          { idU: user.id },
          { $set: { "vip.date": 0, "vip.hasVip": false } }
        );
      }

      totalPessoas--;
    }, 5000);
  }

**Comment by zSpl1nterUS** [comment]
Projeto Descotinuado
